### ISSUE TITLE
how to enable css background images

### ISSUE THREAD

**Issue by mohanzeal** [westy92/html-pdf-chrome#138] opened 2018-04-03 18:47 UTC
I am using google-chrome-beta 66.0 version to generate pdf. Headers and footer are getting applied but not css background images from external site.

can you please example how to enable css image backgrounds like below
.content {
background: url('http://example.com/abc.png');
}

**Comment by mohanzeal** [comment] 2018-04-03 19:09
how to enable backgroud graphics checkbox which can be done while print.

![image](https://user-images.githubusercontent.com/5113135/38270286-87f988e8-37a0-11e8-832e-70d64bdd0fc7.png)

**Comment by westy92** [comment] 2018-04-03 19:12
Duplicate of #25.

Set `printBackground` to `true`.
https://github.com/westy92/html-pdf-chrome/blob/master/src/typings/chrome/Page/PrintToPDFOptions.ts#L32

```typescript
await htmlPdf.create(html,  { 
   printOptions: {
      printBackground: true,
  }
})
```

**Closed** 2018-04-03 19:12 UTC
