### ISSUE TITLE
Implement Timeout

### ISSUE THREAD

**Issue by popsail** [westy92/html-pdf-chrome#6] opened 2017-06-12 23:44 UTC
Hi,
for my use case, i'm trying to generate a pdf report which is now in html with lots of ajax calls.
When using the library I'm getting a blank page as everything is rendered through ajax (it's an angularjs web app).

I implemented a hacky timeout option with setTimeout.
I changed the javascript directly and it's my first time touching generators so I won't post my own code.
Would be lovely if someone implemented a non-hacky solution.

**Comment by tomasc** [comment] 2017-06-14 10:51
I needed it as well and hacked it in via adding timeout after the loadEventFired:

```js
yield new Promise(resolve => {
  setTimeout(() => { resolve() }, options.timeout);
})
```

Not sure if this is the best way to implement this ...

**Comment by westy92** [comment] 2017-06-14 13:31
Is the timeout desired for the page rendering, the PDF generation, or the entire process?

**Comment by tomasc** [comment] 2017-06-14 13:39
The `loadEventFired` does not guarantee that all assets/parts of a page are loaded (esp. when some pieces are pulled in via AJAX as @popsail mentions, images loaded by something like lazysizes, web-fonts etc.). 

Therefore it might be good to have a chance to specify arbitrary wait time after the `loadEventFired`, which would allow to hold off the rendering until after the time we guess the page might be fully assembled.

Possibly, in next versions, it might be an idea to have a chance to specify optional callback to wait for, which can be triggered from within the page to notify the generator that the page is ready to be rendered to PDF.

**Comment by westy92** [comment] 2017-06-14 16:47
Could you provide a minimal example of a page that isn't fully rendering before the PDF is generated?

**Comment by tomasc** [comment] 2017-06-14 16:54
not exactly a minimal example, but see https://fonts.google.com

without timeout (screenshot of generated PDF):
![screen shot 2017-06-14 at 12 53 30](https://user-images.githubusercontent.com/3788/27144611-897989d4-5100-11e7-9b6c-39d14f78cb5c.png)


with 5s timeout:
![screen shot 2017-06-14 at 12 54 17](https://user-images.githubusercontent.com/3788/27144629-9971f04c-5100-11e7-821b-6215389790b5.png)

**Comment by westy92** [comment] 2017-06-16 15:46
I see a few options here to signify page load completion:

- Wait for the page to fire a specific event
- Wait for the page to call a specified callback
- Wait for a specific DOM element to appear on the page
- Wait for a specified amount of time, regardless of what happens on the page

In all cases, I think we should specify a timeout for how long to wait until giving up.

I'm slightly leaning towards the event, but that wouldn't be possible for the use case of external pages with source out of your control.

I think the best option would be to allow the user to pick which of these options to use.

**Comment by tomasc** [comment] 2017-06-16 15:47
agreed!

**Comment by westy92** [comment] 2017-06-16 20:10
I began implementation.

You can specify an optional `CompletionTrigger` in the `CreateOptions`.

```ts
const options: HtmlPdf.CreateOptions = {
  port: 9123,
  completionTrigger: new HtmlPdf.CompletionTrigger.Timer(5000), // milliseconds
};
```

```ts
const options: HtmlPdf.CreateOptions = {
  port: 9123,
  completionTrigger: new HtmlPdf.CompletionTrigger.Event(
    'myEvent', // name of the event to listen for
    'myElementId', // optional DOM element ID to listen on, defaults to body
    5000 // optional timeout
  ),
};
```

**Comment by tomasc** [comment] 2017-06-17 11:11
This is great, thank you.

Especially having a chance to listen to named event will be very helpful -- the only suggestion I would have is to replace elementId with css selector -- (ie `body`, `.my_class`, `#my_id`). Is there a small library that could help facilitate this? (I am still stuck on jQuery so not sure what the vanilla JS options are.)

**Comment by westy92** [comment] 2017-06-17 15:28
I have updated the PR!  Fortunately there's a native `document.querySelector()` I didn't know about.  I updated my above comment as well.

**Comment by tomasc** [comment] 2017-06-17 15:30
Great, thank you, I will give it a try!

(I wrote a small Ruby gem to generate PDF in Rails: https://github.com/tomasc/dragonfly_chrome_headless)

**Comment by westy92** [comment] 2017-06-17 18:14
I added the `Callback` `CompletionTrigger`.  It defines a callback for the browser to call to signify rendering is complete.

```js
const options: HtmlPdf.CreateOptions = {
  port: 9123,
  completionTrigger: new HtmlPdf.CompletionTrigger.Callback(
    'cbName', // optional, name of the callback to define for the browser to call when finished rendering.  Defaults to 'htmlPdfCb'.
    5000 // optional, timeout (milliseconds)
  ),
};
```

**Comment by westy92** [comment] 2017-06-20 03:37
I added the `Element` `CompletionTrigger`.  It listens for an element to be added to the DOM to signify rendering is complete.

```js
const options: HtmlPdf.CreateOptions = {
  port: 9123,
  completionTrigger: new HtmlPdf.CompletionTrigger.Element(
    'div#myElement', // name of the DOM element to wait for
    5000 // optional, timeout (milliseconds)
  ),
};
```

**Comment by tomasc** [comment] 2017-06-20 14:03
Very nice. When do you plan the next release?

**Comment by westy92** [comment] 2017-06-20 14:11
I'm hoping to within the next few days.
https://github.com/westy92/html-pdf-chrome/milestones

**Comment by tomasc** [comment] 2017-06-20 14:29
I see, 👍🏻

**Comment by webernir** [comment] 2017-07-05 07:54
@westy92 [phantom-html-to-pdf](https://www.npmjs.com/package/phantom-html-to-pdf#programmatic-pdf-printing) has another nice [mechanism](https://www.npmjs.com/package/phantom-html-to-pdf#programmatic-pdf-printing):
we can wait to a specific global variable to be set to true.
```javascript
const options: HtmlPdf.CreateOptions = {
  waitForJS: true, //set to true to enable programmatically specify (via Javascript of the page) when the pdf printing starts (see Programmatic pdf printing section for an example) 
  waitForJSVarName: //name of the variable that will be used as a printing trigger, defaults to "PHANTOM_HTML_TO_PDF_READY" (see Programmatic pdf printing section for an example) 
};
```

**Comment by westy92** [comment] 2017-07-05 13:48
@webernir great idea!  I have added it to the list of things to implement with this PR.

**Comment by westy92** [comment] 2017-07-10 05:11
@webernir I added the `Variable` `CompletionTrigger`.  It listens for a variable to be set to `true` to signify rendering is complete.

```js
const options: HtmlPdf.CreateOptions = {
  port: 9123,
  completionTrigger: new HtmlPdf.CompletionTrigger.Variable(
    'myVarName', // optional, name of the variable to wait for.  Defaults to 'htmlPdfDone'
    5000 // optional, timeout (milliseconds)
  ),
};
```

**Comment by webernir** [comment] 2017-07-10 05:15
@westy92 wow! that seems awesome. i'm gonna check it out.
BTW, if I reach the timeout - will it throw an exception, or take the snapshot to that instant moment?

**Comment by westy92** [comment] 2017-07-10 05:17
@webernir it will throw an exception.  Adding an option to take a snapshot on timeout instead would be a new feature request.

**Comment by webernir** [comment] 2017-07-10 05:20
@westy92 great. i guessed that this is the expected behavior. for some reason it worked _not_ as expected so was just making sure.
Thanks!

**Comment by westy92** [comment] 2017-07-10 05:23
@webernir make sure you're on my branch since this hasn't been released yet.  Here's one of the tests verifying the timeout exception: https://github.com/westy92/html-pdf-chrome/pull/9/commits/cec8854e295794e5b3b60f6e87109fdd8edf1f79#diff-19decbba8c9c92fe107dafab0e595e54R450.

**Comment by webernir** [comment] 2017-07-10 05:25
@westy92 i am on your branch.
I was thinking it's because I'm spinning up chrome using `chrome-launcher` myself. still needs to be figured out.

**Comment by westy92** [comment] 2017-07-10 05:36
@webernir how you launch Chrome should not matter, as long as you make note of the port it is launched on and pass that to the htmlPdf options.  If this `CompletionTrigger` is not operating as expected, please provide a minimal code sample so I may verify and fix.

**Comment by westy92** [comment] 2017-07-11 05:35
@popsail @tomasc @mrmnml @chadfawcett @daveboling @kulturpessimist @webernir
I have completed implementation in https://github.com/westy92/html-pdf-chrome/pull/9.  If any of you would like to glance at it and leave comments, that would be great!  I plan to merge it in about 24 hours.

**Comment by tomasc** [comment] 2017-07-11 07:44
@westy92 looks fantastic, I have no comments, only thank you :-)

**Comment by westy92** [comment] 2017-07-11 23:06
Closed in #9.

**Closed by westy92** 2017-07-11 23:06 UTC
Labels: enhancement

**Comment by westy92** [comment] 2017-07-14 06:51
Released in https://github.com/westy92/html-pdf-chrome/releases/tag/v0.2.0!

**Comment by webernir** [comment] 2017-08-17 08:51
https://github.com/GoogleChrome/puppeteer

**Comment by westy92** [comment] 2017-08-23 03:39
@webernir see https://github.com/westy92/html-pdf-chrome/issues/36

**Comment by adamreisnz** [comment] 2017-10-15 00:28
Is there any reliable way to check for when external fonts/stylesheet has loaded? Or do we have to use an arbitrary timeout?

**Comment by adamreisnz** [comment] 2017-10-15 00:33
I've resolved this by using a JS font loader instead, and setting a variable when loaded:

```js
<script type="text/javascript">
    window.WebFontConfig = {
      google: {families: ['Open+Sans:300,600']},
      active: function() {
        window.fontsLoaded = true;
      },
    };
    (function(d) {
      let wf = d.createElement('script');
      let s = d.scripts[0];
      wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js';
      wf.async = true;
      s.parentNode.insertBefore(wf, s);
    }(document));
  </script>
```

Seems to have done the trick.
