### ISSUE TITLE
RTL font not working in headerTemplate

### ISSUE THREAD

**Issue by baravak** [westy92/html-pdf-chrome#281] opened 2020-07-13 08:55 UTC
```
printOptions: {
      displayHeaderFooter: true,
      headerTemplate: `
        <div class="text center" style="font-family:Dana">
          سلام <span class="pageNumber" style="font-family:Iransans; color:red; direction:ltr"></span> / <span class="totalPages" style="font-family:tahoma"></span>
        </div>
      `,
      footerTemplate: '<div class="text center" style="color:green">Custom <i>footer</i>!</div>',
    },
```
pageNumber not showed

**Comment by westy92** [comment] 2021-04-02 06:13
It seems to be working fine for me:
![image](https://user-images.githubusercontent.com/290167/113386647-4dfc9e00-9350-11eb-86e4-e07508d7ed16.png)

Source:
```ts
const html = `
  <html>
    <head>
      <title>TITLE</title>
    </head>
    <body>
      <div style="page-break-after:always">P1</div>
      <div style="page-break-after:always">P2</div>
      <div>P3</div>
    </body>
  </html>
`;
const result = await HtmlPdf.create(html, {
  port,
  printOptions: {
    displayHeaderFooter: true,
    headerTemplate: `
      <div class="text center" style="font-family:Dana">
        سلام <span class="pageNumber" style="font-family:Iransans; color:red; direction:ltr"></span> / <span class="totalPages" style="font-family:tahoma"></span>
      </div>
    `,
    footerTemplate: '<div class="text center" style="color:green">Custom <i>footer</i>!</div>',
  },
});
result.toFile('test.pdf');
```

**Comment by westy92** [comment] 2021-04-18 04:40
Closing due to no customer response. If you continue to see this issue, please comment here with some sample code to reproduce it! Thank you.

**Closed by westy92** 2021-04-18 04:40 UTC
